### PR TITLE
Add dependencies needed for sublime-markdown-popups

### LINKED ISSUE #320: Add "pymdownx" and "pyyaml" in dependencies
Hi!

Please add `pymdownx` and `pyyaml` in dependencies. `dependencies.json` should look like thi:

```json
{
    "*": {
        ">=3119": [
            "markupsafe",
            "mdpopups",
            "pygments",
            "python-jinja2",
            "python-markdown",
            "pymdownx",
            "pyyaml"
        ]
    }
}
```
Without this I see in console `ImportError: No module named 'yaml'` and mdpopups not work.

See: https://github.com/facelessuser/sublime-markdown-popups/blob/master/docs/src/markdown/api.md

### PR DESCRIPTION
**Pull request by berendkleinhaneveld**
This fixes #320 and makes the markdown popups a lot nicer!

### CODE REVIEW

**Comment by berendkleinhaneveld** [comment]
I also found #245 which might be related: seems like a dependency was missing. Maybe the original author installed some other extensions after first encountering the bug and pulled in the needed dependencies and that's the real reason he didn't encounter the problem instead of by upgrading Sublime Text? 🤷 So maybe that issue might also be closed by this PR.

**Comment by berendkleinhaneveld** [comment]
Does anyone want to take a look at this?

**Comment by srusskih** [comment]
Oh my... One year passed. Just checked. It works :)

**Comment by srusskih** [comment]
Thank you for the PR!

**Comment by berendkleinhaneveld** [comment]
Thank you for building this plugin in the first place! Glad to be able to contribute!

**Pull request merged**
