### PR TITLE
Adds `only_complete_after_regex` setting

### PR DESCRIPTION
**Pull request by kylebebak**
Adds a setting, `only_complete_after_regex`, that makes it easier to get around slowdown issues with JEDI.

This allows the user to only trigger auto-completions **immediately after** a character that matches a pattern they specify.

For example, they can enter `"only_complete_after_regex": "\\."` into `sublime_jedi.sublime-settings` to only enable auto-completion after the `.` char.

I didn't add info about this setting to the README because I'm not sure where it should go or how it should be formatted.

### CODE REVIEW

**Comment by kylebebak** [comment]
@srusskih 

Hey, any thoughts on this PR? Only showing autocomplete options after the `.` char has handled perf issues quite well for me in the last few weeks.

It seems like these issues have to do with Jedi and not Sublime Jedi, so I have my doubts about whether we can do much about them.

I tried to change the API as little as possible. I also noticed that [the build is failing](https://travis-ci.com/srusskih/SublimeJEDI/builds/106317743), but it doesn't look like it's related to the code in this PR.

**Comment by srusskih** [comment]
@kylebebak sorry. had no time look into. 

yeah, tests a flaky on TravisCI :( a bit

Nice idea to turnoff ONLY code completion in this way.
Could you please add a some instruction how to use it in README?

**Comment by kylebebak** [comment]
Gladly, will do =)

**Comment by kylebebak** [comment]
@srusskih 

Hey again! Any chance this can get merged? Or is there anything I need to change before we merge it?

**Comment by srusskih** [comment]
@kylebebak sorry for that. Thanks for PR and your commitment :)

**Comment by kylebebak** [comment]
Right on, thanks!

**Pull request merged**
