### PR TITLE
Update jedi to v0.13.1

### PR DESCRIPTION
**Pull request by magnetikonline**
Change to update Jedi package to v0.13.1.

**Note:** this does cause an issue, where Jedi has now dropped support for [Python 3.3](https://github.com/davidhalter/jedi/pull/1019) - so had to patch `access.py` [here](https://github.com/magnetikonline/SublimeJEDI/blob/8584dad2c16f60940a4fcd393f79579bddbd17cc/dependencies/jedi/evaluate/compiled/access.py#L8-L9) and [here](https://github.com/magnetikonline/SublimeJEDI/blob/8584dad2c16f60940a4fcd393f79579bddbd17cc/dependencies/jedi/evaluate/compiled/access.py#L37-L39).

- Can only assume that SublimeText 3 comes packaged with an earlier point release of Python 3?
- Technically this does also mean the `Makefile` won't work as is without patching of the `jedi` package.

Otherwise, all good.

### CODE REVIEW

**Comment by magnetikonline** [comment]
That's not a bad idea @edelvalle - the only alternative I guess is produce a `patch` file from the mainline to the version I've constructed and roll that into the `Makefile` (download mainline, apply `patch`).

Regardless, it's working well this branch for me - sure there is some solution worth doing. 👍

**Comment by srusskih** [comment]
Thanks!
I have couple questions:

* https://github.com/davidhalter/jedi/pull/1019/files#diff-8bb3cd6a401ec9f9abb26c380f7878e4L154 
` find_module = find_module_py33 if is_py33 else find_module_pre_py33 `
how about this ?

*  `types.DynamicClassAttribute` was used for Python >=3.4. Now, in the path, It applies only for >=3.5. can it be an issue for Python 3.4 users?

* https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0130-2018-10-02
> Default environments are now using the same Python version as the Python process. In 0.12.x, we used to load the latest Python version on the system.
if no setting provided, will it fails on SublimeText's Python?

**Comment by srusskih** [comment]
@magnetikonline  Thanks a lot! 👍

**Comment by magnetikonline** [comment]
No dramas @srusskih - a bit flat out with other items at the moment, but it's on my todo list! Using SL Jedi in anger the last week with this patched branch, it's been working really well.

**Comment by magnetikonline** [comment]
Just rebased `master` in here. Sorry, still finding time to round this out!

**Comment by srusskih** [comment]
I hope complete it during next couple weeks, have started https://github.com/srusskih/SublimeJEDI/tree/jedi-0.13.x

**Comment by srusskih** [comment]
@magnetikonline 
just updated `daemon.py` - please try, if it works for you. thanks :)

**Comment by edelvalle** [comment]
I'm testing, seems to be ok... Tomorrow will use it the whole day.... let's see

**Comment by magnetikonline** [comment]
Nice work @srusskih - I'll switch branches now for today..... will report back!

**Comment by magnetikonline** [comment]
Just noted 0.13.2 released of Jedi.

https://github.com/davidhalter/jedi/releases/tag/v0.13.2

**Comment by edelvalle** [comment]
I can confirm too...
working all good!

**Comment by magnetikonline** [comment]
I've just merged in https://github.com/davidhalter/jedi/releases/tag/v0.13.2 to my branch to give that a test - also including your changes too from your https://github.com/srusskih/SublimeJEDI/tree/jedi-0.13.x branch.

**Comment by magnetikonline** [comment]
Been successfully running `0.13.2` for the last day in branch above ☝️ @srusskih I'd say it's safe to merge in those Jedi upstream release changes into your branch.

**Comment by srusskih** [comment]
@magnetikonline I think we can merge your PR, If you do not mind.

**Comment by magnetikonline** [comment]
@srusskih let's do it. All running solid here.

**Comment by magnetikonline** [comment]
Argh! Left out your `.patch` file... trying again.

**Pull request merged**
